Join 'gemini-tunnel' and 'hermione-tunnel' plugins into 'ssh-tunneler'
gemini-testing/ssh-tunneler pull request #1
Opened 2016-12-07 10:25 UTC by eGavr

+ добавил возможность декорировать не только `hostname` в итоговом урле.

сс @j0tunn

2016-12-08 12:10 UTC, j0tunn requested changes
Тесты посмотрел по диагонали, вроде норм.

2016-12-08 12:10 UTC, j0tunn commented on lib/tunnel/index.js
> +        this._tool = tool;
зачем тебе сюда прокидывать `tool`, если тебе рально нужен только `tool.config`?

2016-12-08 12:10 UTC, j0tunn commented on README.md
> +            urlDecorators: {
очень сложная настройка получается. Нужно либо объект с простыми свойствами, либо одна функция. Но объект с функциями - это ад. Пускай этот декоратор принимает целый урл. Кому надо - тот распарсит и поправит

2016-12-08 12:51 UTC, eGavr commented on README.md
> +            urlDecorators: {
Такая настройка более гибкая получается и позволяет упростить конфиг `hermione`.

В текущей реализации конфиг вот такой примерно пролучается:

```js
urlDecorators: {
     hostname: (baseUrl, sshTunnel) => `${sshTunnel.user}-${sshTunnel.port}-si.ldev.yandex.ru`,
    port: 443
}
```

Если передавать весь урл, то в самом конфиге нужно что-то парсить, получается длиннее.

2016-12-08 12:53 UTC, j0tunn commented on README.md
> +            urlDecorators: {
она получается наоборот негибкая, т.к. ты можешь переопределить только то, что позволяет плагин. Обычно подход такой: типа можешь переопределить вот таки и таки опции, или берешь функцию и переопределяешь как хочешь. Да в конфиге кода будет 3 строчки вместо двух, ну и ок

2016-12-09 10:05 UTC, eGavr commented on README.md
> +            urlDecorators: {
> ты можешь переопределить только то, что позволяет плагин

не, там такая реализация, что можно переопределять любую часть урла на самом деле.

но сейчас спорить про это неуместно, так как согласен, что не надо оверинженирить, сделаю твой вариант :)

2016-12-09 13:37 UTC, eGavr commented
@j0tunn 🆙

2016-12-09 14:06 UTC, j0tunn requested changes

2016-12-09 14:06 UTC, j0tunn commented on lib/tunnel/gemini-tunnel.js
> +// remove after https://github.com/gemini-testing/gemini/issues/555#issuecomment-263381235
а давай мы не будем разбивать на классы, а просто в 'gemini.js' вкорячим локальный костыль перед созданием туннеля, который добавить геттер и сеттер `baseUrl`, указывающие на `rootUrl`

2016-12-09 14:06 UTC, j0tunn commented on lib/url-decorator.js
> +    const urlDecorator = opts.urlDecorator && _.isFunction(opts.urlDecorator) ? opts.urlDecorator : defaultDecorator;
т.е. если вместо `urlDecorator`'а в конфиге какое-то г*но, то мы это просто молча проигнорируем? Кажется это нужно унести в валидатор опций на самый верх

2016-12-09 14:06 UTC, j0tunn commented on README.md
> +### hermione
зачем дубировать? напиши, что конфигурация одинаковая и для hermione и для gemini

2016-12-12 11:10 UTC, eGavr commented
🆙

2016-12-12 12:45 UTC, merged